const APP_VERSION='1.4';
const empty={income:0,savings:0,bills:0,transactions:[],budgets:[['Logement',0,0],['Alimentation',0,0],['Transport',0,0],['Restaurants',0,0],['Loisirs',0,0]],goals:[],setupDone:false};
const old=JSON.parse(localStorage.getItem('kbpflow')||'null');
let state=old||JSON.parse(JSON.stringify(empty));let current='home';
const money=n=>new Intl.NumberFormat('fr-CA',{style:'currency',currency:'CAD'}).format(Number(n)||0);
const spent=()=>state.transactions.filter(x=>x.amount<0).reduce((s,x)=>s-x.amount,0);
const available=()=>state.income-state.bills-state.savings-spent();
function save(){localStorage.setItem('kbpflow',JSON.stringify(state))}
function shell(title,body){return `<div class="section-title"><h2>${title}</h2></div>${body}`}
function setup(){return `${shell('Bienvenue dans KBP Flow',`<div class="card"><p class="muted">Commençons avec trois informations. Tu pourras tout modifier ensuite.</p><form id="setupform" class="form"><label>Revenus mensuels<input name="income" type="number" min="0" step="0.01" value="0" required></label><label>Factures prévues<input name="bills" type="number" min="0" step="0.01" value="0" required></label><label>Épargne souhaitée<input name="savings" type="number" min="0" step="0.01" value="0" required></label><button class="btn">Créer mon budget</button></form></div>`)}`}
function home(){if(!state.setupDone)return setup();let a=available();return `<section class="hero"><small>Disponible à dépenser</small><div class="amount">${money(a)}</div><small>Après dépenses, factures prévues et épargne</small></section><div class="grid"><div class="card"><span class="muted">Revenus</span><div class="metric good">${money(state.income)}</div></div><div class="card"><span class="muted">Dépenses</span><div class="metric">${money(spent())}</div></div><div class="card"><span class="muted">Épargne prévue</span><div class="metric">${money(state.savings)}</div></div><div class="card"><span class="muted">Factures à venir</span><div class="metric">${money(state.bills)}</div></div></div>${shell('Vue rapide',`<div class="card"><div class="row"><span>Prévision fin de mois</span><strong class="${a>=0?'good':'expense'}">${money(a)}</strong></div><div class="row"><span>Objectifs actifs</span><strong>${state.goals.length}</strong></div><div class="row"><span>Conseil KBP Flow</span><span class="pill">${a<0?'Budget à rééquilibrer':'Garde une marge avant tout achat'}</span></div></div>`)}`}
function transactions(){return `${shell('Ajouter une transaction',`<div class="card"><form id="txform" class="form"><input name="name" placeholder="Description" required><select name="type"><option value="expense">Dépense</option><option value="income">Revenu</option></select><input name="amount" type="number" min="0.01" step="0.01" placeholder="Montant" required><select name="cat"><option>Alimentation</option><option>Logement</option><option>Transport</option><option>Restaurants</option><option>Loisirs</option><option>Abonnements</option><option>Autres</option></select><button class="btn">Ajouter</button></form></div>`)}${shell('Transactions',`<div class="card">${state.transactions.length?state.transactions.map((t,i)=>`<div class="row transaction"><div><strong>${t.name}</strong><div class="muted">${t.cat}</div></div><div><span class="amount ${t.amount>0?'income':'expense'}">${t.amount>0?'+':''}${money(t.amount)}</span> <button class="ghost" style="color:#777" onclick="delTx(${i})">×</button></div></div>`).join(''):'<p class="muted">Aucune transaction pour le moment.</p>'}</div>`)}`}
function budget(){return `${shell('Budget mensuel',`<div class="card">${state.budgets.map(b=>{let p=b[2]>0?Math.min(100,Math.round(b[1]/b[2]*100)):0;return `<div class="row"><div style="width:100%"><div style="display:flex;justify-content:space-between"><strong>${b[0]}</strong><span>${money(b[1])} / ${money(b[2])}</span></div><div class="progress"><i style="width:${p}%"></i></div></div></div>`}).join('')}</div>`)}${shell('Paramètres rapides',`<div class="card"><form id="budgetform" class="form"><label>Revenus mensuels<input name="income" type="number" min="0" step="0.01" value="${state.income}"></label><label>Épargne prévue<input name="savings" type="number" min="0" step="0.01" value="${state.savings}"></label><label>Factures à venir<input name="bills" type="number" min="0" step="0.01" value="${state.bills}"></label><button class="btn">Mettre à jour</button></form></div>`)}`}
function goals(){return `${shell('Objectifs d’épargne',`<div class="card">${state.goals.length?state.goals.map(g=>{let p=Math.min(100,Math.round(g[1]/g[2]*100));return `<div class="row"><div style="width:100%"><div style="display:flex;justify-content:space-between"><strong>${g[0]}</strong><span>${p}%</span></div><div class="muted">${money(g[1])} / ${money(g[2])}</div><div class="progress"><i style="width:${p}%"></i></div></div></div>`}).join(''):'<p class="muted">Aucun objectif. Ajoute ton premier objectif ci-dessous.</p>'}</div>`)}${shell('Nouvel objectif',`<div class="card"><form id="goalform" class="form"><input name="name" placeholder="Nom de l’objectif" required><input name="saved" type="number" min="0" step="0.01" placeholder="Déjà économisé" required><input name="target" type="number" min="1" step="0.01" placeholder="Objectif total" required><button class="btn">Ajouter l’objectif</button></form></div>`)}`}
function more(){return `${shell('KBP Flow',`<div class="card"><div class="row"><span>Catégories</span><b>›</b></div><div class="row"><span>Factures récurrentes</span><b>›</b></div><div class="row"><span>Alertes</span><b>›</b></div><div class="row"><span>Rapports</span><b>›</b></div><div class="row"><span>Paramètres</span><b>›</b></div></div>`)}${shell('KBP Flow Pro',`<div class="card"><strong style="color:var(--purple)">Bientôt</strong><p class="muted">Prévisions avancées, assistant intelligent et automatisations pourront être ajoutés plus tard.</p></div>`)}`}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===current));document.querySelector('#view').innerHTML=({home,transactions,budget,goals,more}[current])();bind()}
function bind(){let f=document.querySelector('#setupform');if(f)f.onsubmit=e=>{e.preventDefault();let d=new FormData(f);state.income=+d.get('income');state.bills=+d.get('bills');state.savings=+d.get('savings');state.setupDone=true;save();render()};f=document.querySelector('#txform');if(f)f.onsubmit=e=>{e.preventDefault();let d=new FormData(f),a=+d.get('amount');state.transactions.unshift({name:d.get('name'),cat:d.get('cat'),amount:d.get('type')==='income'?a:-a});save();render()};f=document.querySelector('#budgetform');if(f)f.onsubmit=e=>{e.preventDefault();let d=new FormData(f);state.income=+d.get('income');state.savings=+d.get('savings');state.bills=+d.get('bills');state.setupDone=true;save();render()};f=document.querySelector('#goalform');if(f)f.onsubmit=e=>{e.preventDefault();let d=new FormData(f);state.goals.push([d.get('name'),+d.get('saved'),+d.get('target')]);save();render()}}
window.delTx=i=>{state.transactions.splice(i,1);save();render()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{current=b.dataset.view;render()});document.querySelector('#reset').onclick=()=>{if(confirm('Effacer toutes les données et recommencer à zéro ?')){localStorage.removeItem('kbpflow');state=JSON.parse(JSON.stringify(empty));current='home';render()}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render();
